#!/bin/bash

#add path where data are stored
path=/Users/leandrojorqueravalero/Desktop/PhD/Retroelement_engineering/RT_exploration/Miseq-data-GWRIII

#create assocative array
declare -A output

for fastq in $(ls $path/GWR-TEST-III-{1,2,3,4,5,6,7,8,9,10}_*R1*)

do
# define WT sequence; zgrep for looking for seq, wc -w for counting the number of matches 
WT=$(zgrep -i GAAGGGCTCCCAT $fastq | wc -w)
#echo $WT
# same for desired edited sequence
edited=$(zgrep -i GAAGTGCTCCCAT $fastq | wc -w)
# print the number of edited sequences
#echo $edited
# define the percentage of edited sequences and open calculate with bc mode
percent=$(echo "scale=3 ;($edited / ($WT + $edited))*100 " | bc)
# print percentage
#echo  $(basename $fastq)    $percent

#include the results into the array
output[$(basename $fastq)]=$percent
done

#loop for printing array
for key in "${!output[@]}"; do echo $key ' - ' ${output["$key"]} 
done | sort -rn -k3
