#!/bin/bash
#define path where fastq files are stored
path=/Users/leandrojorqueravalero/Desktop/PhD/Miseq/IsrB_DSB_test/second_try

#define loop for files QC
for fastq in $(ls $path/Pool7*)
do

fastqc $fastq
done

#create folder to store fastqc results and move it to path (we are in NGS code folder) 
cd $path
mkdir fastqc_output

#moving .zip files to new directory previously created(fastqc_output)
for file in $(ls $path/*.zip)
do

mv $file $path/fastqc_output
done

cd $path/fastqc_output

#with multiqc . we scan the whole directory
multiqc .

#remove .zip files from fastqc_output directory after multiQC
for zip in $(ls $path/fastqc_output/*.zip*)
do

rm $zip
done

#remove .html files from each fastqc created in parent directory 
 
for html in $(ls $path/*fastqc.html)
do

rm $html
done
