#!/bin/bash
#define path where fastq files are stored
path=/Users/leandrojorqueravalero/Desktop/PhD/Miseq/Miseq_optimization

#define loop for files QC
for fastq $(ls $path)
do

fastqc $fastq

done
mkdir fastqc_files

#Creating multiqc report from fastqc output (fastqc.zip files) previously saved in a folder
#moving .zip files to new directory
for *.zip in $path
do

mv *.zip fastc_files

done

multiqc $(ls fastqc_files)

