#!/bin/bash
#define path where fastq files are stored or execute from this folder to make it simpler
path=/Users/leandrojorqueravalero/Desktop/PhD/Miseq/RT_test/RT-test3

#define loop for files QC
for fastq in $(ls ./*_R1_*)
do

fastqc $fastq
done

#create folder to store fastqc results and move it to path (we are in NGS code folder) 
#cd $path
mkdir fastqc_output

#moving .zip files to new directory previously created(fastqc_output)
for file in $(ls ./*.zip)
do

mv $file ./fastqc_output
done

cd ./fastqc_output

#with multiqc . we scan the whole directory
multiqc .

#remove .zip files from fastqc_output directory after multiQC
#for zip in $(ls $path/fastqc_output/*.zip*)
#do

#rm $zip
#done

#remove .html files from each fastqc created in parent directory 
 
for html in $(ls $path/*fastqc.html)
do

rm $html
done
