#!/bin/bash

# Auto-generated script to run CRISPRessoBatch for Prime Editing
CRISPRessoBatch \
    --batch_settings "/Users/leandro/Desktop/github/NGS-data/SeV-ORF1_251003/merged/crispresso.batch" \
    --output_folder "/Users/leandro/Desktop/github/NGS-data/SeV-ORF1_251003" \
    --amplicon_seq "TCTACGTCTGATTGGTGTACCTGAAAGTGATGTGGAGAATGGAACCAAGTTGGAAAACACTCTGCAGGATATTATCCAGGAGAACTTCCCCAATCTAGCAAGGCAGGCCAACGTTCAGATTCAGGAAATACAGAGAACGCCACAAAGATACTCCTCGAGAAGAGCAACTCCAAGACACATAATTGTCAGATTCACCAAAGTTGAA" \
    --prime_editing_override_prime_edited_ref_seq "TCTACGTCTGATTGGTGTACCTGAAAGTGATGTGGAGAATGGAACCAAGTTGGAAAACACTCTGCAGGATATTATCCAGGAGAACTTCCCCAACTTATCTAGCAAGGCAGGCCAACGTTCAGATTCAGGAAATACAGAGAACGCCACAAAGATACTCCTCGAGAAGAGCAACTCCAAGACACATAATTGTCAGATTCACCAAAGTTGAAA" \
    --prime_editing_pegRNA_spacer_seq "CAAUCUAGCAAGGCAGGCC" \
    --prime_editing_pegRNA_extension_seq "CTGCCTTGCTAGATAAGTTGGGGAAGTTCTC" \
    --prime_editing_pegRNA_scaffold_seq "GTTTTAGAGCTAGAAATAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGAAAAAGTGGCACCGAGTCGGTGC" \
    --quantification_window_center "-1" \
    --quantification_window_size "5" \

