#!/bin/bash

# Auto-generated script to run CRISPRessoBatch for Prime Editing
CRISPRessoBatch \
    --batch_settings "/Users/leandro/Desktop/github/NGS-data/RTtest6-sorted/merged/crispresso.batch" \
    --output_folder "/Users/leandro/Desktop/github/NGS-data/RTtest6-sorted/merged" \
    --amplicon_seq "GAAACGCCCATGCAATTAGTCTATTTCTGCTGCAAGTAAGCATGCATTTGTAGGCTTGATGCTTTTTTTCTGCTTCTCCAGCCCTGGCCTGGGTCAATCCTTGGGGCCCAGACTGAGCACGTGATGGCAGAGGAAAGGAAGCCCTGCTTCCTCCAGAGGGCGTCGCAGGACAGCTTTTCCTAGACAGGGGCTAGTATGTGCAGCTCCTGCACCGGGATACTGGTTGACAAGTTTGGCTGGGCTGGAAGCCAGCACCTAGGGAGGTCCCTGGAAGGGGCCAGCCTCACCAGGAGAGGAGGGACCTGGCCCTTCAGGGTCGAGCT" \
    --prime_editing_override_prime_edited_ref_seq "GAAACGCCCATGCAATTAGTCTATTTCTGCTGCAAGTAAGCATGCATTTGTAGGCTTGATGCTTTTTTTCTGCTTCTCCAGCCCTGGCCTGGGTCAATCCTTGGGGCCCAGACTGAGCACGCTTGTGATGGCAGAGGAAAGGAAGCCCTGCTTCCTCCAGAGGGCGTCGCAGGACAGCTTTTCCTAGACAGGGGCTAGTATGTGCAGCTCCTGCACCGGGATACTGGTTGACAAGTTTGGCTGGGCTGGAAGCCAGCACCTAGGGAGGTCCCTGGAAGGGGCCAGCCTCACCAGGAGAGGAGGGACCTGGCCCTTCAGGGTCGAGCTC" \
    --prime_editing_pegRNA_spacer_seq "GGCCCAGACTGAGCACGTGA" \
    --prime_editing_pegRNA_extension_seq "TCTGCCATCAcaagCGTGCTCAGTCTG" \
    --prime_editing_pegRNA_scaffold_seq "GTTTTAGAGCTAGGCCAACATGAGGATCACCCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCACGCCGAAAGGCGGGCACCGAGTCGGTGC" \
    --quantification_window_center "-1" \
    --quantification_window_size "5" \

