#!/bin/bash
#add path where data are stored
path=/homes/users/ljorquera/scratch/data/RT_test1/

#create assocative array
declare -A output

# Calculate the number of reads containing the edited sequence in the control sample
for fastq in $(ls $path/Pool-4-1*)
do
spont=$(zgrep -i GAAGtGCTCCCAT $fastq | wc -w)
        #echo $spont
done

# Total number of reads and reads containing the edit in each sample
for fastq in $(ls $path/Pool-4*)
do
total=$(zgrep '^@' $fastq | wc -l)
  echo "Number of reads is" $total
edited=$(zgrep -i GAAGtGCTCCCAT $fastq - $spont | wc -w)
  echo "Number of edited reads is" $edited 
# define the percentage of edited sequences and open calculate with bc mode
efficiency=$(echo "scale=3 ;(($edited - $spont) / $total)*100 " | bc)
        #echo  $(basename $fastq)    $efficiency

#include the results into the array
output[$(basename $fastq)]=$efficiency
done

#loop for printing array
for key in "${!output[@]}"; do echo $key ' - ' ${output["$key"]} 
done | sort -rn -k3 > editing_ouput.txt

#moving file to path directory 
#mv editing_output.txt $path
open editing_output.txt

